apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-do
  name: prometheus
  namespace: monitoring
spec:
  rules:
    - host: {{ fqdn_prometheus }}
      http:
        paths:
          - backend:
              serviceName: prometheus-operated
              servicePort: 9090
            path: /
  tls:
    - hosts:
        - {{ fqdn_prometheus }}
      secretName: {{ fqdn_prometheus }}-tls
