apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-do
  name: grafana
  namespace: monitoring
spec:
  rules:
    - host: {{ fqdn_grafana }}
      http:
        paths:
          - backend:
              serviceName: prometheus-operator-grafana
              servicePort: 3000
            path: /
  tls:
    - hosts:
        - {{ fqdn_grafana }}
      secretName: {{ fqdn_grafana }}-tls
