---
- name: "Use aptitude"
  apt:
    pkg: "aptitude"
    state: latest
  when: ansible_os_family == 'Debian'

- name: "Install software packages"
  package:
    name: "*"
    state: "latest"
  when: update_all_packages

- name: "Install package updates only"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ update_packages }}"
