- name: Install CertManager Manifests
  shell: kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/v0.13.0/deploy/manifests/00-crds.yaml

- name: Add JetStack Repo for Helm
  shell: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm Repo
  shell: helm repo update

- name: Install CertManager
  shell: helm upgrade --install --wait cert-manager jetstack/cert-manager --namespace cert-manager --version v0.13.0

- name: Install ClusterIssuer
  k8s:
    state: present
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: cluster-issuer-do.yml
