apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-do
spec:
  acme:
    email: {{ email_letsencrypt }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-do
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token
              key: token
