- name: K8s Post Install Scripts
  hosts: master-1.k8s.dev
  become: yes
  vars:
    email_letsencrypt: sergey@larionov.biz
    fqdn_prometheus: prometheus.devoid.info
    fqdn_grafana: grafana.devoid.info
    fqdn_docker_registry: docker-registry.devoid.info
  roles:
    - role: k8s-firewall
      tags: [ k8s-firewall ]
    - role: k8s-cert-manager
      tags: [ k8s-cert-manager ]
    - role: k8s-prometheus
      tags: [ k8s-prometheus ]
    - role: k8s-docker-registry
      tags: [ k8s-docker-registry ]
