- name: K8s Init Firewall
  hosts: k8s-cluster
  become: yes
  roles:
    - role: k8s-firewall
      tags: [ k8s-firewall ]

- name: K8s Post Install
  hosts: kube-master[0]
  become: true
  vars:
    email_letsencrypt: sergey@larionov.biz
    fqdn_prometheus: prometheus.devoid.info
    fqdn_grafana: grafana.devoid.info
    fqdn_docker_registry: docker-registry.devoid.info
  roles:
    - role: k8s-cert-manager
      tags: [ k8s-cert-manager ]
    - role: k8s-prometheus
      tags: [ k8s-prometheus ]
    - role: k8s-docker-registry
      tags: [ k8s-docker-registry ]
